Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0f34c5ae932e6f0e4
      InstanceType: t2.micro
      SubnetId: subnet-03eaf58707279875e
      SecurityGroupIds: 
        - sg-03604b4ce08f54704
      KeyName: jez